trigger:
  branches:
    include:
      - development
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.11'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: $(pythonVersion)
              addToPath: true

          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            displayName: 'Install dependencies'

          - script: |
              pytest
            displayName: 'Run Tests'

  - stage: Deploy_Development
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/development')
    jobs:
      - deployment: DevelopmentDeployment
        environment: Development
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'Azure subscription 1'
                    appName: 'flaskapp-deploy-test'
                    package: $(System.DefaultWorkingDirectory)/**/*.zip

  - stage: Deploy_Production
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    jobs:
      - deployment: ProductionDeployment
        environment: Production
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'Azure subscription 1'
                    appName: 'flaskapp-deplpoy-prod'
                    package: $(System.DefaultWorkingDirectory)/**/*.zip
